project:
  type: website
  output-dir: docs

website:
  title: "Kostas Sechidis"
  favicon: /img/thumbnail.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: "{{< ai CV >}} About me"
      - publications.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 1
    toc_float: true

editor: visual

