---
title: "Publications"
---
# 2026
-   Chen Y, Sun S, **Sechidis K**, Zhang C, Hothorn T & Bornkamp B.\
    *Comparing Methods to Assess Treatment Effect Heterogeneity in General Parametric Regression Models* 
     **Statistics in Medicine** 45, no. 1-2 (2026): e70381, doi:[10.1002/sim.7038](https://doi.org/10.1002/sim.7038), [arXiv](https://arxiv.org/abs/2503.22548).

-   Svensson D, Hermansson E, Nikolaou N, **Sechidis K** & Lipkovich I.\
    *Overview and practical recommendations on using Shapley Values for identifying predictive biomarkers via CATE modelings*\
     **Statistics in Medicine** 45, no. 1-2 (2026): e70375, doi:[10.1002/sim.70375](https://doi.org/10.1002/sim.70375), [arXiv](https://arxiv.org/abs/2505.01145).

# 2025
-    **Sechidis K**, Sun S, Chen Y, Lu J, Zhang C, Baillie M, Ohlssen D, Vandemeulebroecke M, Hemmings R, Ruberg S & Bornkamp B.\
     *WATCH: A Workflow to Assess Treatment Effect Heterogeneity in Drug Development for Clinical Trial Sponsors*\
     **Pharmaceutical Statistics**. 2025. doi:[10.1002/pst.2463](https://doi.org/10.1002/pst.2463), [arXiv](https://doi.org/10.48550/arXiv.2405.00859)

-    **Sechidis K**, Zhang C, Sun S, Chen Y, Spector A & Bornkamp B.\
     *Using Individualized Treatment Effects to Assess Treatment Effect Heterogeneity*\
     **Statistics in Medicine** 44, no. 28-30 (2025): e70324, doi:[https://doi.org/10.1002/sim.70324](https://doi.org/10.1002/sim.70324), [arXiv](https://arxiv.org/abs/2502.00713)

-    Müller MM, Bornkamp B, Bretz F, Cannings TI, Liu W, Reeve HWJ, Samworth RJ, Sfikas N, Wan F & **Sechidis K**.\
     *Data‑driven controlled subgroup selection in clinical trials*\
     [arXiv](https://arxiv.org/abs/2512.15676)

-   Fischer L. & **Sechidis K**.\
    *Knockoffs for low dimensions: changing the nominal level post-hoc to gain power while controlling the FDR*\
    [arXiv](https://arxiv.org/abs/2511.11166)

-   Parola A, Jessen ET, Rybner A, Mortensen MD, Larsen SN, Simonsen A, Lin JM, Zhou Y, Wang H, Koelkebeck K, **Sechidis K**, Bliksted V & Fusaroli R.\
    *Vocal Markers of Schizophrenia: Assessing the Generalizability of Machine Learning Models and Their Clinical Applicability.*\
    **Schizophrenia Bulletin**. 2025. doi:[https://doi.org/10.1093/schbul/sbaf124](https://doi.org/10.1093/schbul/sbaf124)

-   Morán-Fernández L, Blanco-Mallo E, **Sechidis K** & Bolón-Canedo V. \
    *Breaking boundaries: Low-precision conditional mutual information for efficient feature selection.*\
    **Patter Recognition**. 2025. doi:[0.1016/j.patcog.2025.111375](https://doi.org/10.1016/j.patcog.2025.111375)

# 2024     
-    Zimmermann MR, Baillie M, Kormaksson M, Ohlssen D & **Sechidis K**. \
    *All that Glitters Is not Gold: Type I Error Controlled Variable Selection from Clinical Trial Data.*\
    **Clinical Pharmacology and Therapeutics**. 2024. doi:[10.1002/cpt.3211](https://doi.org/10.1002/cpt.3211)
    
-   Sun S, **Sechidis K**, Chen Y, Lu J, Ma C, Mirshani A, Ohlssen D, Vandemeulebroecke M, & Bornkamp B.\
    *Comparing algorithms for characterizing treatment effect heterogeneity in randomized trials.*\
    **Biometrical Journal**. 2024; 66, 2100337. doi:[10.1002/bimj.202100337](https://doi.org/10.1002/bimj.202100337)

# 2022

-   Hansen L, Zhang Y-P, Wolf D, **Sechidis K**, Ladegaard N, Fusaroli R.\
    *A generalizable speech emotion recognition model reveals depression and remission.*\
    **Acta Psychiatrica Scandinavica**. 2022; 145: 186--199. doi:[10.1111/acps.13388](https://doi.org/10.1111/acps.13388)

# 2021

-   **Sechidis K**, Kormaksson M, Ohlssen D.\
    *Using knockoffs for controlled predictive biomarker identification.*\
    **Statistics in Medicine**. 2021; 40(25): 5453--5473. doi:[10.1002/sim.9134](https://doi.org/10.1002/sim.9134), [code](https://github.com/sechidis/2021-SiM-Predictive-Knockoffs)

-   **Sechidis K**, Fusaroli R, Orozco-Arroyave JR, Wolf D, Zhang YP.\
    *A machine learning perspective on the emotional content of Parkinsonian speech.*\
    **Artificial Intelligence in Medicine**. 2021; 115:102061. doi:[10.1016/j.artmed.2021.102061](https://doi.org/10.1016/j.artmed.2021.102061)

# 2020

-   Moran-Fernandez L, **Sechidis K**, Bolon-Canedo V, Alonso-Betanzos A, Brown G.\
    *Feature selection with limited bit depth mutual information for portable embedded systems.*\
    **Knowledge-Based Systems**. 2020; 197:105885. doi:[10.1016/j.knosys.2020.105885](https://doi.org/10.1016/j.knosys.2020.105885)

-   Spyromitros-Xioufis E, **Sechidis K**, Vlahavas I.\
    *Multi-target regression via output space quantization.*\
    **International Joint Conference on Neural Networks** (IJCNN). 2020. IEEE. doi:[10.1109/IJCNN48605.2020.9206984](https://doi.org/10.1109/IJCNN48605.2020.9206984)

-   Morán-Fernández L, Blanco-Mallo E, **Sechidis K**, Alonso-Betanzos A, Bolón-Canedo V.\
    *When Size Matters: Markov Blanket with Limited Bit Depth Conditional Mutual Information.*\
    **ECML/PKDD 2020 ITEM Workshop**: Streams for Data-Driven Predictive Maintenance and IoT, Edge, and Mobile for Embedded Machine Learning. doi:[10.1007/978-3-030-66770-2_18](https://doi.org/10.1007/978-3-030-66770-2_18)

-   Nikolaou N, **Sechidis K**.\
    *Inferring Causal Direction from Observational Data: A Complexity Approach.*\
    **ECML/PKDD 2020 PharML Workshop**: Machine Learning for Pharma and Healthcare Applications. doi:[10.48550/arXiv.2010.05635](https://doi.org/10.48550/arXiv.2010.05635)

# 2019

-   **Sechidis K**, Azzimonti L, Pocock A, Corani G, Weatherall J, Brown G.\
    *Efficient feature selection using shrinkage estimators.*\
    **Machine Learning Journal** (MLJ). 2019; 108: 1261--1286. doi:[10.1007/s10994-019-05795-1](https://doi.org/10.1007/s10994-019-05795-1), [code](https://github.com/sechidis/2019-MLJ-Efficient-feature-selection-using-shrinkage-estimators)

-   **Sechidis K**, Spyromitros-Xioufis E, Vlahavas I.\
    *Information Theoretic Multi-Target Feature Selection via Output Space Quantization.*\
    **Entropy**. 2019; 21(9):855. doi:[10.3390/e21090855](https://doi.org/10.3390/e21090855), [code](https://github.com/sechidis/2019-Entropy-Multi-target-feature-selection)

-   Bolon-Canedo V, **Sechidis K**, Sanchez-Marono N, Alonso-Betanzos A,Brown G.\
    *Insights into distributed feature ranking.*\
    **Information Sciences**. 2019;496:378-398. doi:[10.1016/j.ins.2018.09.045](https://doi.org/10.1016/j.ins.2018.09.045)

-   **Sechidis K**, Papangelou K, Nogueira S, Weatherall J, Brown G.\
    *On the Stability of Feature Selection in the Presence of Feature Correlations.*\
    **Machine Learning and Knowledge Discovery in Databases**. European Conference on Machine Learning and Principles and Practice of Knowledge Discovery (ECML/PKDD) 2019. doi:[10.1007/978-3-030-46150-8_20](https://doi.org/10.1007/978-3-030-46150-8_20)., [code](https://github.com/sechidis/2019-ECML-Stability-correlations)\
    **Acceptance rate 130/734 (18%)**

-   **Sechidis K**, Spyromitros-Xioufis E, Vlahavas I.\
    *Multi-target feature selection through output space clustering.*\
    **European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning** (ESANN). 2019. [paper](https://www.esann.org/sites/default/files/proceedings/legacy/es2019-20.pdf)

# 2018

-   **Sechidis K**, Papangelou K, Metcalfe PD, Svensson D, Weatherall J, Brown G.\
    *Distinguishing prognostic and predictive biomarkers: an information theoretic approach.*\
    **Bioinformatics**, 2018; 34(19): 3365--3376. doi:[10.1093/bioinformatics/bty357](https://doi.org/10.1093/bioinformatics/bty357), [code](https://github.com/sechidis/2018-Bioinformatics-Predictive-Biomarker-Discovery)

-   **Sechidis K**, Brown G.\
    *Simple strategies for semi-supervised feature selection.*\
    **Machine Learning Journal** (MLJ). 2018; 107(2): 357-395. doi:[10.1007/s10994-017-5648-2](https://doi.org/10.1007/s10994-017-5648-2), [code](https://github.com/sechidis/2018-MLJ-Semi-supervised-feature-selection)

-   Nogueira S, **Sechidis K**, Brown G.\
    *On the Stability of Feature Selection Algorithms.*\
    **Journal of Machine Learning Research** (JMLR).2018; 18(174):1-54. [paper](https://jmlr.org/papers/v18/17-514.html)

-   Papangelou K, **Sechidis K**, Weatherall J, Brown G.\
    *Toward an Understanding of Adversarial Examples in Clinical Trials.*\
    **Machine Learning and Knowledge Discovery in Databases**. European Conference on Machine Learning and Principles and Practice of Knowledge Discovery (ECML/PKDD) 2018. doi:[10.1007/978-3-030-10925-7_3](https://doi.org/10.1007/978-3-030-10925-7_3).\
    **Acceptance rate 92/354 (26%)**

# 2017

-   **Sechidis K**, Sperrin M., Petherick ES, Luján M., Brown, G.\
    *Dealing with under-reported variables: An information theoretic solution.*\
    **International Journal of Approximate Reasoning**, 2017. 8;159-177. doi:[10.1016/j.ijar.2017.04.002](https://doi.org/10.1016/j.ijar.2017.04.002), [code](https://github.com/sechidis/2017-IJAR-Under-reported-variables)

-   Bolon-Canedo V, **Sechidis K**, Sanchez-Marono N, Alonso-Betanzos A, Brown G.\
    *Exploring the consequences of distributed feature selection in DNA microarray data.*\
    **International Joint Conference on Neural Networks** (IJCNN). 2017. IEEE. doi:[10.1109/IJCNN.2017.7966051](https://doi.org/10.1109/IJCNN.2017.7966051)

-   **Sechidis K**, Turner E, Metcalfe PD, Svensson D, Weatherall J, Brown G.\
    *Disentangling Prognostic and Predictive Biomarkers Through Mutual Information.*\
    **Informatics for Health** (I4H). 2017. doi:[10.3233/978-1-61499-753-5-141](https://doi.org/10.3233/978-1-61499-753-5-141)

-   Nogueira S, **Sechidis K**, Brown G.\
    *On the Use of Spearman's Rho to Measure the Stability of Feature Rankings.*\
    **Iberian Conference on Pattern Recognition and Image Analysis** (IbPRIA) 2017. doi:[10.1007/978-3-319-58838-4_42](https://doi.org/10.1007/978-3-319-58838-4_42)

-   Bolon-Canedo V, Remeseiro B, **Sechidis K**, Martinez-Rego D, Alonso-Betanzos A.\
    *Algorithmic challenges in Big Data analytics.*\
    **European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning** (ESANN) 2017. [paper](https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2017-6.pdf)

# 2016

-   **Sechidis K**, Sperrin M., Petherick ES, Luján M., Brown, G.\
    *Estimating mutual information in under-reported variables.*\
    **International Conference on Probabilistic Graphical Models** (PGM) 2016. [paper](http://proceedings.mlr.press/v52/sechidis16.pdf)

-   **Sechidis K**, Turner E, Metcalfe PD, Svensson D, Weatherall J, Brown G.\
    *Ranking Biomarkers Through Mutual Information.*\
    **NeurIPS Workshop on Machine Learning for Health (ML4HC)** 2016. doi:[10.48550/arXiv.1612.01316](https://doi.org/10.48550/arXiv.1612.01316)

# 2015

-   **Sechidis K**, Brown G.\
    *Markov blanket discovery in positive-unlabelled and semi-supervised data.*\
    **Machine Learning and Knowledge Discovery in Databases**. European Conference on Machine Learning and Principles and Practice of Knowledge Discovery (ECML/PKDD) 2015. doi:[10.1007/978-3-319-23528-8_22](https://doi.org/10.1007/978-3-319-23528-8_22).\
    **Acceptance rate 89/383 (23.2%).**

-   **Sechidis K**.\
    *Hypothesis Testing and Feature Selection in Semi-supervised Data.*\
    **PhD Thesis, School of Computer Science, University of Manchester, UK**. [thesis](https://research.manchester.ac.uk/en/studentTheses/hypothesis-testing-and-feature-selection-in-semi-supervised-data).\
    PhD supervisor: Professor [Gavin Brown](https://profgavinbrown.github.io/).\
    [**AWARD: Best PhD Thesis Prize of the School of Computer Science at the University of Manchester 2016 (sponsored by IBM)**](https://studentnet.cs.manchester.ac.uk/pgr/symposium/prizes.php)

# 2014

-   **Sechidis K**, Calvo B, Brown G.\
    *Statistical Hypothesis Testing in Positive Unlabelled Data.*\
    **Machine Learning and Knowledge Discovery in Databases**. European Conference on Machine Learning and Principles and Practice of Knowledge Discovery (ECML/PKDD) 2014. doi:[10.1007/978-3-662-44845-8_5](https://doi.org/10.1007/978-3-662-44845-8_5).\
    **Acceptance rate 115/483 (23.8%)**\
    **AWARD: Best Student Paper Award in ECML/PKDD 2014 (sponsored by Springer).**\
    **AWARD: Runner up Best Paper Prize of the School of Computer Science at the University of Manchester 2014 (sponsored by IBM).**

-   **Sechidis K**, Nikolaou N, Brown G.\ 
    *Information theoretic feature selection in multi-label data through composite likelihood.*\
   **Structural, Syntactic, and Statistical Pattern Recognition** (SSPR) 2014. doi:[10.1007/978-3-662-44415-3_15](https://doi.org/10.1007/978-3-662-44415-3_15)

# 2011

-   **Sechidis K**, Tsoumakas G, Vlahavas I.\
    *On the Stratification of Multi-label Data.*\
    **Machine Learning and Knowledge Discovery in Databases**. European Conference on Machine Learning and Principles and Practice of Knowledge Discovery (ECML/PKDD) 2011. doi:[10.1007/978-3-642-23808-6_10](https://doi.org/10.1007/978-3-642-23808-6_10).\
    **Acceptance rate 121/599 (20%).**

-   Spyromitros-Xioufis E, **Sechidis K**, Tsoumakas G, Vlahavas I.\
    *MLKDs Participation at the CLEF 2011 Photo Annotation and Concept-Based Retrieval Tasks.*\
    **ImageClef Lab of CLEF Conference on Multilingual and Multimodal Information Access Evaluation**. [paper](http://ceur-ws.org/Vol-1177/CLEF2011wn-ImageCLEF-Spyromitros-XioufisEt2011.pdf)

-   **Sechidis K**.\
    *Multi-label machine learning algorithms for automated image annotation.*\
    **MSc Thesis, School of Informatics, Aristotle University of Thessaloniki, Greece**. [thesis](http://ikee.lib.auth.gr/record/126696?ln=en).\
    Thesis supervisor: Professor [Grigorios Tsoumakas](https://intelligence.csd.auth.gr/people/tsoumakas/).\
